name: rails-example
proxy:
  appserver:
    - rails.lndo.site:3000
services:
  appserver:
    type: compose
    services:
      image: bitnami/rails
      command: "bundle exec rails server -b 0.0.0.0 -p 3000"
      user: root
      environment:
        BUNDLE_DEFAULT_INSTALL_USERS_PATH: /app/vendor
        DATABASE_HOST: database
        DATABASE_NAME: rails
    build:
      - bundle install
  database:
    type: mariadb
    creds:
      user: rails
      password: rails
      database: rails
  sidekiq:
    type: compose
    services:
      image: bitnami/rails
      command: bundle exec sidekiq
tooling:
  rails:
    service: appserver
  bundle:
    service: appserver
  rake:
    service: appserver